services:
    db:
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=clinica
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3307:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
        interval: 5s
        timeout: 5s
        retries: 10
      networks:
        - app_network

    gethora:
      build:
        context: ./getHora
      ports:
        - "5001:5000"
      volumes:
        - ./getHora:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    sethora:
      build:
        context: ./setHora
      ports:
        - "5000:5000"
      volumes:
        - ./setHora:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    getmedico:
      build:
        context: ./getMedico
      ports:
        - "5002:5000"
      volumes:
        - ./getMedico:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    setmedico:
      build:
        context: ./setMedico
      ports:
        - "5003:5000"
      volumes:
        - ./setMedico:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    getempleado:
      build:
        context: ./getEmpleado
      ports:
        - "5004:5000"
      volumes:
        - ./getEmpleado:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    setempleado:
      build:
        context: ./setEmpleado
      ports:
        - "5005:5000"
      volumes:
        - ./setEmpleado:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
        
    gethorario:
      build:
        context: ./getHorario
      ports:
        - "5006:5000"
      volumes:
        - ./getHorario:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

    backsetpaciente:
      build:
        context: ./backsetPaciente
      ports:
        - "5008:5000"
      volumes:
        - ./backsetPaciente:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    detallemedico:
      build:
        context: ./detalleMedico
      ports:
        - "5009:5000"
      volumes:
        - ./detalleMedico:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    detallehora:
      build:
        context: ./detalleHora
      ports:
        - "5013:5000"
      volumes:
        - ./detalleHora:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    setcitamedica:
      build:
        context: ./setCitaMedica
      ports:
        - "5011:5000"
      volumes:
        - ./setCitaMedica:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    getcitamedica:
      build:
        context: ./getCitaMedica
      ports:
        - "5012:5000"
      volumes:
        - ./getCitaMedica:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    sethorario:
      build:
        context: ./setHorario
      ports:
        - "5014:5000"
      volumes:
        - ./setHorario:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    getanalisis:
      build:
        context: ./getAnalisis
      ports:
        - "5015:5000"
      volumes:
        - ./getAnalisis:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    setanalisis:
      build:
        context: ./setAnalisis
      ports:
        - "5016:5000"
      volumes:
        - ./setAnalisis:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    detalleanalisis:
      build:
        context: ./detalleAnalisis
      ports:
        - "5017:5000"
      volumes:
        - ./detalleAnalisis:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    getmedicamentos:
      build:
        context: ./getMedicamentos
      ports:
        - "5018:5000"
      volumes:
        - ./getMedicamentos:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    setmedicamentos:
      build:
        context: ./setMedicamentos
      ports:
        - "5019:5000"
      volumes:
        - ./setMedicamentos:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    detallereceta:
      build:
        context: ./detalleReceta
      ports:
        - "5020:5000"
      volumes:
        - ./detalleReceta:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    clientlogin:
      build:
        context: ./clientLogin
      ports:
        - "5050:5000"
      volumes:
        - ./clientLogin:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    clientinicio:
      build:
        context: ./clientInicio
      ports:
        - "5051:5000"
      volumes:
        - ./clientInicio:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    clientpanel:
      build:
        context: ./clientPanel
      ports:
        - "5052:5000"
      volumes:
        - ./clientPanel:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    clientcitamedica:
      build:
        context: ./clientCitaMedica
      ports:
        - "5053:5000"
      volumes:
        - ./clientCitaMedica:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network
    clienttablacitas:
      build:
        context: ./clientTablaCitas
      ports:
        - "5054:5000"
      volumes:
        - ./clientTablaCitas:/app
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=clinica
        - DB_USER=root
        - DB_PASSWORD=root
      command: python manage.py runserver 0.0.0.0:5000
      networks:
        - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge