# Generated by Django 5.2.1 on 2025-07-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('codTipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipoAnalisis', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
    ]
