# Generated by Django 5.2.1 on 2025-07-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numHor', models.IntegerField()),
                ('codMed', models.IntegerField()),
                ('codHor', models.IntegerField()),
                ('consul', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'detallehora',
            },
        ),
    ]
