# Generated by Django 5.2.1 on 2025-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('codReceta', models.AutoField(primary_key=True, serialize=False)),
                ('id_medi', models.IntegerField()),
            ],
            options={
                'db_table': 'detallereceta',
            },
        ),
    ]
