# Generated by Django 5.2.1 on 2025-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('codHora', models.AutoField(primary_key=True, serialize=False)),
                ('horaIni', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
            options={
                'db_table': 'hora',
            },
        ),
    ]
