# Generated by Django 5.2.1 on 2025-07-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAnalisis',
            fields=[
                ('codAnalisis', models.AutoField(primary_key=True, serialize=False)),
                ('codTipo', models.IntegerField()),
            ],
            options={
                'db_table': 'detalleanalisis',
            },
        ),
    ]
