# Generated by Django 5.2.1 on 2025-05-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabarApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='pass_field',
            new_name='clave',
        ),
    ]
