# Generated by Django 5.2.1 on 2025-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('codAte', models.AutoField(primary_key=True, serialize=False)),
                ('codCita', models.IntegerField()),
                ('codReceta', models.IntegerField()),
                ('codAnalisis', models.IntegerField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=150)),
                ('t_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'atencionmedica',
            },
        ),
    ]
