# Generated by Django 5.2.1 on 2025-07-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencionmedica',
            old_name='codReceta',
            new_name='id_receta',
        ),
    ]
