# Generated by Django 5.2.1 on 2025-05-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('codMed', models.AutoField(primary_key=True, serialize=False)),
                ('nomMed', models.CharField(max_length=100)),
                ('especial', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
    ]
