# Generated by Django 5.2.1 on 2025-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medi', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.CharField(max_length=10)),
                ('fec_ven', models.DateTimeField()),
                ('nombre', models.CharField(max_length=100)),
                ('t_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
    ]
