# Generated by Django 5.2.1 on 2025-07-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('codCita', models.AutoField(primary_key=True, serialize=False)),
                ('numHor', models.CharField(max_length=10)),
                ('codMed', models.CharField(max_length=10)),
                ('codHor', models.CharField(max_length=10)),
                ('codPago', models.CharField(max_length=10)),
                ('consultorio', models.CharField(max_length=5)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('t_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cita_medica',
            },
        ),
    ]
