# Generated by Django 5.2.1 on 2025-07-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='dni',
            field=models.CharField(default='12345678', max_length=10),
        ),
    ]
