# Generated by Django 5.2.1 on 2025-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citaApp', '0002_citamedica_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='codPago',
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
