# Generated by Django 5.2.1 on 2025-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citaApp', '0003_remove_citamedica_codpago_alter_citamedica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
