# Generated by Django 5.2.1 on 2025-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienteApp', '0002_alter_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cargo',
            field=models.CharField(default='paciente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
