# Generated by Django 5.2.1 on 2025-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codEmp', models.AutoField(primary_key=True, serialize=False)),
                ('nomEmp', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('pass_field', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
